preprocessor:
    classes:
        - Jazz
        - Pop
    pickle_store_folder: 'clean/2-bar/clean_midi_1'
    include_unknown: True
    only_unknown: True
    low_crop: 24 
    high_crop: 84
    num_notes: 128
    smallest_note: 16
    max_velocity: 127
    include_only_monophonic_instruments: False
    max_voices_per_track: 4
    max_voices: 1
    include_silent_note: True
    velocity_threshold: 0.5
    instrument_attach_method: '1hot-category'
    attach_instruments: False
    input_length: &T 32 #256 # Number of beats. We want to split songs into 16 bars of 16th notes
    output_length: *T
    test_fraction: 0.1
    include_held_note: False
    
trainer:
    learning_rate: 0.0005 #0.0005 #0.001
    KL_rate: 0.9999
    KL_end: 0.2
    free_bits: 1024 #256
    sampling_rate: 2000 #2000
    batch_size: &batchsize 2
    print_every: 100
    checkpoint_every: 5000
    plot_every: 1
    checkpoint_dir: 'checkpoint'
    output_dir: 'scratch/outputs/baseline_tests_march'
    use_danceability: &DA False
    use_fake_data: False
    use_grad_clip: True
    scale_tf: .9
    use_regularizer: False
    regularizer_weight: 0.2
    use_target_smoothing: False
    fixed_tf_prob: False
    
sampler:
    free_bits: 256
    output_dir: 'sampler'
    
model:
    num_subsequences: 16
    max_sequence_length: *T
    sequence_length: 16
    encoder_input_size: 61
    decoder_input_size: 61
    encoder_hidden_size: 2048
    decoder_hidden_size: 1024
    latent_dim: 512
    encoder_num_layers: 2
    decoder_num_layers: 2
    use_danceability: *DA
    dropout_p: .1

data: # Specify paths to data
    train_data: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/X_train.pickle'
    val_data: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/X_test.pickle'
    train_instrument_data: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/I_train.pickle'
    val_instrument_data: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/I_test.pickle'
    train_tempo_data: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/T_train.pickle'
    val_tempo_data: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/T_test.pickle'
    train_song_paths: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/train_paths.pickle'
    val_song_paths: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/test_paths.pickle'
    train_extra_features: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/extra_features_train.pickle'
    val_extra_features: '/Users/stefanwijtsma/code/magenta-torch/clean/clean_midi_1/extra_features_test.pickle'


das-data:
    train_data: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/X_train.pickle'
    val_data: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/X_test.pickle'
    train_instrument_data: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/I_train.pickle'
    val_instrument_data: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/I_test.pickle'
    train_tempo_data: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/T_train.pickle'
    val_tempo_data: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/T_test.pickle'
    train_song_paths: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/train_paths.pickle'
    val_song_paths: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/test_paths.pickle'
    train_extra_features: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/extra_features_train.pickle'
    val_extra_features: '/home/swa420/magenta-torch/scratch/data/clean_midi_1/extra_features_test.pickle'



evaluation:
    model_path: '/Users/stefanwijtsma/code/magenta-torch/outputs/checkpoints/2020_07_31_01_13_30/model.pt'
    test_data: 'pickles/X_test.pickle'
    test_instruments: 'pickles/I_test.pickle'
    test_songs: 'pickles/test_paths.pickle'
    test_tempos: 'pickles/T_test.pickle'
    batch_size: *batchsize
    temperature: 1.0
    reconstruction:
        attach_method: '1hot-category'
        song_name: "/Users/stefanwijtsma/code/mt/data/clean_midi/Johnny Hates Jazz/I Don't Want to Be a Hero.mid"
        reconstruction_path: 'midi_reconstruction'
        
    

