preprocessor:
    classes:
        - Jazz
        - Pop
    pickle_store_folder: 'data_november/happy_birthday'
    include_unknown: True
    only_unknown: True
    low_crop: 24 
    high_crop: 84
    num_notes: 128
    smallest_note: 16
    max_velocity: 127
    include_only_monophonic_instruments: False
    max_voices_per_track: 1
    max_voices: 4
    include_silent_note: True
    velocity_threshold: 0.5
    instrument_attach_method: '1hot-category'
    attach_instruments: False
    input_length: &T 256 # Number of beats. We want to split songs into 16 bars of 16th notes
    output_length: *T
    test_fraction: 0.2
    
trainer:
    learning_rate: 0.000001 #0.001
    KL_rate: 0.9999
    free_bits: 256
    sampling_rate: 2000
    batch_size: &batchsize 2
    print_every: 1
    checkpoint_every: 1000000
    plot_every: 1
    checkpoint_dir: 'checkpoint'
    output_dir: 'scratch/outputs/november_happy_bday'
    use_danceability: &DA False
    use_fake_data: False
    
sampler:
    free_bits: 256
    output_dir: 'sampler'
    
model:
    num_subsequences: 16
    max_sequence_length: *T
    sequence_length: 16
    encoder_input_size: 61
    decoder_input_size: 61
    encoder_hidden_size: 2048
    decoder_hidden_size: 1024
    latent_dim: 512
    encoder_num_layers: 2
    decoder_num_layers: 2
    use_danceability: *DA

data: # Specify paths to data
    train_data: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/X_train.pickle'
    val_data: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/X_test.pickle'
    train_instrument_data: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/I_train.pickle'
    val_instrument_data: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/I_test.pickle'
    train_tempo_data: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/T_train.pickle'
    val_tempo_data: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/T_test.pickle'
    train_song_paths: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/train_paths.pickle'
    val_song_paths: '/Users/stefanwijtsma/code/magenta-torch/pickle_data/new_preprocess_test_32/test_paths.pickle'
    danceability_paths: '/Users/stefanwijtsma/code/mt/extra_features/danceability.pickle'
    filepaths: '/Users/stefanwijtsma/code/mt/extra_features/filenames.pickle'


das-data:
    train_data: '/var/scratch/swa420/data/happy_birthday/X_train.pickle'
    val_data: '/var/scratch/swa420/data/happy_birthday/X_test.pickle'
    train_instrument_data: '/var/scratch/swa420/data/happy_birthday/I_train.pickle'
    val_instrument_data: '/var/scratch/swa420/data/happy_birthday/I_test.pickle'
    train_tempo_data: '/var/scratch/swa420/data/happy_birthday/T_train.pickle'
    val_tempo_data: '/var/scratch/swa420/data/happy_birthday/T_test.pickle'
    train_song_paths: '/var/scratch/swa420/data/happy_birthday/train_paths.pickle'
    val_song_paths: '/var/scratch/swa420/data/happy_birthday/test_paths.pickle'
    danceability_paths: '/var/scratch/swa420/data/colab_data/danceability.pickle'
    filepaths: '/var/scratch/swa420/data/colab_data/filenames.pickle'



evaluation:
    model_path: '/Users/stefanwijtsma/code/magenta-torch/outputs/checkpoints/2020_07_31_01_13_30/model.pt'
    test_data: 'pickles/X_test.pickle'
    test_instruments: 'pickles/I_test.pickle'
    test_songs: 'pickles/test_paths.pickle'
    test_tempos: 'pickles/T_test.pickle'
    batch_size: *batchsize
    temperature: 1.0
    reconstruction:
        attach_method: '1hot-category'
        song_name: "/Users/stefanwijtsma/code/mt/data/clean_midi/Johnny Hates Jazz/I Don't Want to Be a Hero.mid"
        reconstruction_path: 'midi_reconstruction'
        
    

